## numpy基础

In [1]:
import numpy as np    # 调用numpy库

# nparray是numpy中的数组，类似于python中的list与pandas中的series

In [31]:
# 生成随机数组，2x3的矩阵
data_1 = np.random.randn(2, 3)
data_1

array([[ 2.09262678, -0.37507997, -0.80269105],
       [ 0.4763908 ,  0.78464992, -0.71446272]])

In [44]:
# 依次生成从第一个位置参数到第二个位置参数以第三个参数为步长的数组
# arange函数是python内置方法range的数组版
np.arange(2, 10, 2)

array([2, 4, 6, 8])

In [45]:
data_1 * 10    # 可对数组进行四则运算

array([[20.92626778, -3.75079974, -8.02691053],
       [ 4.76390801,  7.84649919, -7.14462721]])



### numpy中array的运算比python中list的运算快10-100倍且占用更少的内存空间

### numpy这个命名空间里包含了大量与python内建函数重名的函数（如max，min）

In [46]:
# 每一个array数组都有一个shape属性，用于表示数组的维度
data_1.shape

(2, 3)

In [47]:
# 每一个array数组都有一个dtype属性，用于表示数组的数据类型
data_1.dtype

dtype('float64')

In [48]:
# np.array函数可以接收任何序列型对象
list_1 = [1, 2, 3, 4]
data_2 = np.array(list_1)
data_2

array([1, 2, 3, 4])

In [49]:
# ndim方法用于输出数组的维度，即行数
data_2.ndim

1

### 生成数组的函数（方法）

In [50]:
# np.zeros用于生成一个全零矩阵
np.zeros(10)

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [51]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [52]:
np.zeros((2, 3, 2))

array([[[0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.]]])

In [53]:
# np.ones生成一个全一矩阵
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [60]:
# asarray方法将输入转化为ndarray型
list_2 = [2, 4, 6, 8]
np.asarray(list_2)

array([2, 4, 6, 8])

In [62]:
# ones_like方法：根据给出的数组生成一个形状完全相同的全1数组
np.ones_like(data_1)

array([[1., 1., 1.],
       [1., 1., 1.]])

In [63]:
# zeros_like方法：根据给出的数组生成一个形状完全相同的全0数组
np.zeros_like(data_1)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [64]:
# empty：根据给出的形状生成一个空数组
np.empty((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [69]:
# empty_like：根据给出的数组生成一个形状完全相同的空数组
np.empty_like(data_1)

array([[0., 0., 0.],
       [0., 0., 0.]])

In [74]:
# full：根据给定的形状和数据生成指定数值的数组
np.full((2, 2), 10)

array([[10, 10],
       [10, 10]])

In [75]:
# full_like：根据给出的数组生成一个形状完全相同的指定数值的数组
np.full_like(data_1, 10)

array([[10., 10., 10.],
       [10., 10., 10.]])

In [76]:
# eye或identity：生成一个NxN的特征矩阵，即单位阵
np.eye(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [77]:
np.identity(2)

array([[1., 0.],
       [0., 1.]])

In [79]:
# 可以在定义数组的同时定义数组中数据类型
np.array([1,3,5,7], dtype = np.float64)

array([1., 3., 5., 7.])

In [85]:
# 可以用astype方法转换数组的数据类型
data_11 = data_1.astype(np.float64)
data_11.dtype

dtype('float64')

### numpy数组算术

In [95]:
arr = np.arange(6)
arr = arr.reshape((2, 3))
arr

array([[0, 1, 2],
       [3, 4, 5]])

In [96]:
arr + arr

array([[ 0,  2,  4],
       [ 6,  8, 10]])

In [97]:
arr * arr

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [99]:
# 带有标量计算的算术操作，会把计算参数传递给数组的每一个元素
arr * 3

array([[ 0,  3,  6],
       [ 9, 12, 15]])